Jar and interface and abstract class
H1mang1/core-java-concepts pull request #5
Opened 2024-08-06 18:07 UTC by H1mang1

2024-08-06 18:07 UTC, H1mang1 commented
@rkpatra201

2024-08-06 18:39 UTC, rkpatra201 approved these changes

2024-08-07 13:57 UTC, merged

2024-08-08 08:16 UTC, rkpatra201 requested changes

2024-08-08 08:17 UTC, rkpatra201 requested changes

2024-08-08 08:17 UTC, rkpatra201 commented on README.md
> +it separates interface from its implementation. it focuses on important characteristics of object hiding the underlyng details that are not relevan to the user.t simplifies  the complexity and promot
Can you justify each of the above line with an example?

2024-08-08 08:17 UTC, rkpatra201 commented on README.md
> +
Can you justify with example